### ISSUE TITLE
Create a tslint for all projects

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/systems#1]
All the projects should follow a consistent styleguide. It would be troublesome to constantly update changes to the styleguide in all projects, so ideally a way to have one source and let the changes propagate should be found.

## Reviewer
Brad

**Comment by ExtraGravity** [comment]
PR Created for common tslint file https://github.com/agriculture-capstone/systems/pull/10

**Comment by ExtraGravity** [comment]
https://github.com/agriculture-capstone/agritrader/pull/26 tslint for trader

**Comment by Parasrah** [comment]
I think this can be resolved? All the repos have linting adhering to the same style guide now :D
