### ISSUE TITLE
Add engines to all package.json

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/systems#15]
To enforce versions of our basic tools (Node, Yarn, npm) we should have the following in all `package.json` files:

```
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.5.1",
    "yarn": ">= 1.3.0"
  },
```

## Reviewer
Bea
## QA
Moath

**Comment by ExtraGravity** [comment]
https://github.com/agriculture-capstone/agritrader/pull/42
https://github.com/agriculture-capstone/agriboard/pull/38
https://github.com/agriculture-capstone/agriculture-core/pull/23
