### ISSUE TITLE
Convert Jenkins to use new Blue Ocean interface

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/systems#4]
https://jenkins.io/projects/blueocean/

**Comment by ExtraGravity** [comment]
Used the jenkins blue ocean docker image for our CI. Transferred users on http://35.190.153.22/. Everyone's old accounts are still there.

**Comment by ExtraGravity** [comment]
Created PR and assigned brad to review https://github.com/agriculture-capstone/systems/pull/9
