### ISSUE TITLE
Figure out what to do with slack 

### ISSUE THREAD

**Issue by beaesguerra** [agriculture-capstone/systems#5]
After 10k messages in slack, we will start losing messages. Figure out if there are any important things we need from there

**Comment by mfalthaw** [comment]
We'll have to export data manually via [here](https://softwarecapstone.slack.com/services/export)

## Description
### Here’s what’s included:
Messages sent in most channels
Files shared in most channels
Archived channels
Integration activity logs

### What’s not included:
Messages and files sent in private channels
Messages and files sent in direct messages
Editing and deletion logs

Your export will consist of a series of JSON files: one per channel per day with activity, plus a file containing information about all members of your workspace. Your engineers will know what to do with these. For information on the format of channel messages, please [consult our API docs.](https://api.slack.com/docs/messages)
