### ISSUE TITLE
Convert Markdown to ASCII Doctor

### ISSUE THREAD

**Issue by jeinglis** [agriculture-capstone/systems#7]

**Comment by ExtraGravity** [comment]
README revamp for agritrader created, assigned to Bea for review.

https://github.com/agriculture-capstone/agritrader/pull/24

**Comment by ExtraGravity** [comment]
README revamp for core created, assigned to Brad for review.

https://github.com/agriculture-capstone/agriculture-core/pull/14

**Comment by ExtraGravity** [comment]
README revamp for dashboard created, assigned to Brad for review.

https://github.com/agriculture-capstone/agriboard/pull/11

**Comment by Parasrah** [comment]
@enochtsang Is there anything to review for this right now or can I move it back to In Progress? It looks like everything is closed
